services:
  rpi-exporter:
    container_name: rpi-exporter
    image: d3vilh/rpi_exporter-arm64:latest
    restart: unless-stopped
    privileged: true
    ports:
      - "9110:9110/tcp"
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 100M
        reservations:
          cpus: 0.25
          memory: 50M
